import Footer_ from './Footer';
import Header_ from './Header';
import Home_ from './Home';
import Library_ from './Library';
import Options_ from './Options';
import Profile_ from './Profile';
import Friends_ from './Friends';
import Recommended_ from './Recommended';
import Splash_ from './Splash';
import Wishlist_ from './Wishlist';

export const Footer = Footer_;
export const Header = Header_;
export const Home = Home_;
export const Library = Library_;
export const Options = Options_;
export const Profile = Profile_;
export const Friends = Friends_;
export const Recommended = Recommended_;
export const Splash = Splash_;
export const Wishlist = Wishlist_;
